# Generated by Django 4.2.4 on 2023-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('completed', models.CharField(max_length=20)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
    ]
