# Generated by Django 4.2.4 on 2023-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxtaskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('completed', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskManage',
        ),
    ]
